version: '3.7'

services:
  terraform:
    image: hashicorp/terraform
    container_name: terraform-muserver
    entrypoint: ''
    command: 'sh'
    volumes:
      - $PWD:/app
    working_dir: /app
    env_file: .env
